template: testify
packages:
    gophermart/internal/infrastructure/storage:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            filename: "mock_{{.InterfaceName | snakecase}}.go"
            pkgname: "mocks"
            structname: "Mock{{.InterfaceName}}"
        interfaces:
            StorageInterface:
    gophermart/internal/infrastructure/accrual:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            filename: "mock_{{.InterfaceName | snakecase}}.go"
            pkgname: "mocks"
            structname: "Mock{{.InterfaceName}}"
        interfaces:
            AccrualClient:
