// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gophermart/internal/infrastructure/accrual"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccrualClient creates a new instance of MockAccrualClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualClient {
	mock := &MockAccrualClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccrualClient is an autogenerated mock type for the AccrualClient type
type MockAccrualClient struct {
	mock.Mock
}

type MockAccrualClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualClient) EXPECT() *MockAccrualClient_Expecter {
	return &MockAccrualClient_Expecter{mock: &_m.Mock}
}

// GetOrderAccrual provides a mock function for the type MockAccrualClient
func (_mock *MockAccrualClient) GetOrderAccrual(ctx context.Context, orderNumber string) (*accrual.AccrualResponse, error) {
	ret := _mock.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderAccrual")
	}

	var r0 *accrual.AccrualResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*accrual.AccrualResponse, error)); ok {
		return returnFunc(ctx, orderNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *accrual.AccrualResponse); ok {
		r0 = returnFunc(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accrual.AccrualResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrualClient_GetOrderAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderAccrual'
type MockAccrualClient_GetOrderAccrual_Call struct {
	*mock.Call
}

// GetOrderAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *MockAccrualClient_Expecter) GetOrderAccrual(ctx interface{}, orderNumber interface{}) *MockAccrualClient_GetOrderAccrual_Call {
	return &MockAccrualClient_GetOrderAccrual_Call{Call: _e.mock.On("GetOrderAccrual", ctx, orderNumber)}
}

func (_c *MockAccrualClient_GetOrderAccrual_Call) Run(run func(ctx context.Context, orderNumber string)) *MockAccrualClient_GetOrderAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccrualClient_GetOrderAccrual_Call) Return(accrualResponse *accrual.AccrualResponse, err error) *MockAccrualClient_GetOrderAccrual_Call {
	_c.Call.Return(accrualResponse, err)
	return _c
}

func (_c *MockAccrualClient_GetOrderAccrual_Call) RunAndReturn(run func(ctx context.Context, orderNumber string) (*accrual.AccrualResponse, error)) *MockAccrualClient_GetOrderAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// MapStatus provides a mock function for the type MockAccrualClient
func (_mock *MockAccrualClient) MapStatus(accrualStatus string) string {
	ret := _mock.Called(accrualStatus)

	if len(ret) == 0 {
		panic("no return value specified for MapStatus")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(accrualStatus)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAccrualClient_MapStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapStatus'
type MockAccrualClient_MapStatus_Call struct {
	*mock.Call
}

// MapStatus is a helper method to define mock.On call
//   - accrualStatus string
func (_e *MockAccrualClient_Expecter) MapStatus(accrualStatus interface{}) *MockAccrualClient_MapStatus_Call {
	return &MockAccrualClient_MapStatus_Call{Call: _e.mock.On("MapStatus", accrualStatus)}
}

func (_c *MockAccrualClient_MapStatus_Call) Run(run func(accrualStatus string)) *MockAccrualClient_MapStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccrualClient_MapStatus_Call) Return(s string) *MockAccrualClient_MapStatus_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAccrualClient_MapStatus_Call) RunAndReturn(run func(accrualStatus string) string) *MockAccrualClient_MapStatus_Call {
	_c.Call.Return(run)
	return _c
}
