// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"gophermart/internal/domain/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageInterface creates a new instance of MockStorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageInterface {
	mock := &MockStorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageInterface is an autogenerated mock type for the StorageInterface type
type MockStorageInterface struct {
	mock.Mock
}

type MockStorageInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageInterface) EXPECT() *MockStorageInterface_Expecter {
	return &MockStorageInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) Close() {
	_mock.Called()
	return
}

// MockStorageInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorageInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorageInterface_Expecter) Close() *MockStorageInterface_Close_Call {
	return &MockStorageInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorageInterface_Close_Call) Run(run func()) *MockStorageInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageInterface_Close_Call) Return() *MockStorageInterface_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorageInterface_Close_Call) RunAndReturn(run func()) *MockStorageInterface_Close_Call {
	_c.Run(run)
	return _c
}

// CreateOrder provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) CreateOrder(ctx context.Context, number string, userID uuid.UUID) error {
	ret := _mock.Called(ctx, number, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, number, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageInterface_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockStorageInterface_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - userID uuid.UUID
func (_e *MockStorageInterface_Expecter) CreateOrder(ctx interface{}, number interface{}, userID interface{}) *MockStorageInterface_CreateOrder_Call {
	return &MockStorageInterface_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, number, userID)}
}

func (_c *MockStorageInterface_CreateOrder_Call) Run(run func(ctx context.Context, number string, userID uuid.UUID)) *MockStorageInterface_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageInterface_CreateOrder_Call) Return(err error) *MockStorageInterface_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageInterface_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, number string, userID uuid.UUID) error) *MockStorageInterface_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) CreateUser(ctx context.Context, login string, passwordHash string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, login, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, login, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, login, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageInterface_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStorageInterface_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - passwordHash string
func (_e *MockStorageInterface_Expecter) CreateUser(ctx interface{}, login interface{}, passwordHash interface{}) *MockStorageInterface_CreateUser_Call {
	return &MockStorageInterface_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, login, passwordHash)}
}

func (_c *MockStorageInterface_CreateUser_Call) Run(run func(ctx context.Context, login string, passwordHash string)) *MockStorageInterface_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageInterface_CreateUser_Call) Return(uUID uuid.UUID, err error) *MockStorageInterface_CreateUser_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockStorageInterface_CreateUser_Call) RunAndReturn(run func(ctx context.Context, login string, passwordHash string) (uuid.UUID, error)) *MockStorageInterface_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithdrawal provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) CreateWithdrawal(ctx context.Context, userID uuid.UUID, order string, sum float64) error {
	ret := _mock.Called(ctx, userID, order, sum)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithdrawal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, float64) error); ok {
		r0 = returnFunc(ctx, userID, order, sum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageInterface_CreateWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithdrawal'
type MockStorageInterface_CreateWithdrawal_Call struct {
	*mock.Call
}

// CreateWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - order string
//   - sum float64
func (_e *MockStorageInterface_Expecter) CreateWithdrawal(ctx interface{}, userID interface{}, order interface{}, sum interface{}) *MockStorageInterface_CreateWithdrawal_Call {
	return &MockStorageInterface_CreateWithdrawal_Call{Call: _e.mock.On("CreateWithdrawal", ctx, userID, order, sum)}
}

func (_c *MockStorageInterface_CreateWithdrawal_Call) Run(run func(ctx context.Context, userID uuid.UUID, order string, sum float64)) *MockStorageInterface_CreateWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorageInterface_CreateWithdrawal_Call) Return(err error) *MockStorageInterface_CreateWithdrawal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageInterface_CreateWithdrawal_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, order string, sum float64) error) *MockStorageInterface_CreateWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) GetBalance(ctx context.Context, userID uuid.UUID) (*models.Balance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *models.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Balance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Balance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageInterface_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockStorageInterface_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStorageInterface_Expecter) GetBalance(ctx interface{}, userID interface{}) *MockStorageInterface_GetBalance_Call {
	return &MockStorageInterface_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *MockStorageInterface_GetBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStorageInterface_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageInterface_GetBalance_Call) Return(balance *models.Balance, err error) *MockStorageInterface_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockStorageInterface_GetBalance_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*models.Balance, error)) *MockStorageInterface_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByNumber provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) GetOrderByNumber(ctx context.Context, number string) (*models.Order, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNumber")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Order, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Order); ok {
		r0 = returnFunc(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageInterface_GetOrderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByNumber'
type MockStorageInterface_GetOrderByNumber_Call struct {
	*mock.Call
}

// GetOrderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockStorageInterface_Expecter) GetOrderByNumber(ctx interface{}, number interface{}) *MockStorageInterface_GetOrderByNumber_Call {
	return &MockStorageInterface_GetOrderByNumber_Call{Call: _e.mock.On("GetOrderByNumber", ctx, number)}
}

func (_c *MockStorageInterface_GetOrderByNumber_Call) Run(run func(ctx context.Context, number string)) *MockStorageInterface_GetOrderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageInterface_GetOrderByNumber_Call) Return(order *models.Order, err error) *MockStorageInterface_GetOrderByNumber_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockStorageInterface_GetOrderByNumber_Call) RunAndReturn(run func(ctx context.Context, number string) (*models.Order, error)) *MockStorageInterface_GetOrderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingOrders provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) GetPendingOrders(ctx context.Context) ([]models.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingOrders")
	}

	var r0 []models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageInterface_GetPendingOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingOrders'
type MockStorageInterface_GetPendingOrders_Call struct {
	*mock.Call
}

// GetPendingOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageInterface_Expecter) GetPendingOrders(ctx interface{}) *MockStorageInterface_GetPendingOrders_Call {
	return &MockStorageInterface_GetPendingOrders_Call{Call: _e.mock.On("GetPendingOrders", ctx)}
}

func (_c *MockStorageInterface_GetPendingOrders_Call) Run(run func(ctx context.Context)) *MockStorageInterface_GetPendingOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageInterface_GetPendingOrders_Call) Return(orders []models.Order, err error) *MockStorageInterface_GetPendingOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockStorageInterface_GetPendingOrders_Call) RunAndReturn(run func(ctx context.Context) ([]models.Order, error)) *MockStorageInterface_GetPendingOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) GetUserByLogin(ctx context.Context, login string) (*models.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageInterface_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockStorageInterface_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockStorageInterface_Expecter) GetUserByLogin(ctx interface{}, login interface{}) *MockStorageInterface_GetUserByLogin_Call {
	return &MockStorageInterface_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, login)}
}

func (_c *MockStorageInterface_GetUserByLogin_Call) Run(run func(ctx context.Context, login string)) *MockStorageInterface_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageInterface_GetUserByLogin_Call) Return(user *models.User, err error) *MockStorageInterface_GetUserByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStorageInterface_GetUserByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (*models.User, error)) *MockStorageInterface_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOrders provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) GetUserOrders(ctx context.Context, userID uuid.UUID) ([]models.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageInterface_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type MockStorageInterface_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStorageInterface_Expecter) GetUserOrders(ctx interface{}, userID interface{}) *MockStorageInterface_GetUserOrders_Call {
	return &MockStorageInterface_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", ctx, userID)}
}

func (_c *MockStorageInterface_GetUserOrders_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStorageInterface_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageInterface_GetUserOrders_Call) Return(orders []models.Order, err error) *MockStorageInterface_GetUserOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockStorageInterface_GetUserOrders_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]models.Order, error)) *MockStorageInterface_GetUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawals provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) GetWithdrawals(ctx context.Context, userID uuid.UUID) ([]models.Withdrawal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []models.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Withdrawal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Withdrawal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageInterface_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type MockStorageInterface_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStorageInterface_Expecter) GetWithdrawals(ctx interface{}, userID interface{}) *MockStorageInterface_GetWithdrawals_Call {
	return &MockStorageInterface_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", ctx, userID)}
}

func (_c *MockStorageInterface_GetWithdrawals_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStorageInterface_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageInterface_GetWithdrawals_Call) Return(withdrawals []models.Withdrawal, err error) *MockStorageInterface_GetWithdrawals_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *MockStorageInterface_GetWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]models.Withdrawal, error)) *MockStorageInterface_GetWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function for the type MockStorageInterface
func (_mock *MockStorageInterface) UpdateOrderStatus(ctx context.Context, number string, status string, accrual *float64) error {
	ret := _mock.Called(ctx, number, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *float64) error); ok {
		r0 = returnFunc(ctx, number, status, accrual)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageInterface_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockStorageInterface_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - status string
//   - accrual *float64
func (_e *MockStorageInterface_Expecter) UpdateOrderStatus(ctx interface{}, number interface{}, status interface{}, accrual interface{}) *MockStorageInterface_UpdateOrderStatus_Call {
	return &MockStorageInterface_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, number, status, accrual)}
}

func (_c *MockStorageInterface_UpdateOrderStatus_Call) Run(run func(ctx context.Context, number string, status string, accrual *float64)) *MockStorageInterface_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *float64
		if args[3] != nil {
			arg3 = args[3].(*float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorageInterface_UpdateOrderStatus_Call) Return(err error) *MockStorageInterface_UpdateOrderStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageInterface_UpdateOrderStatus_Call) RunAndReturn(run func(ctx context.Context, number string, status string, accrual *float64) error) *MockStorageInterface_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}
